### ISSUE TITLE
in opendistro v1.9.0 docker performance analyzer does not bind to 0.0.0.0 with proper settings

### ISSUE THREAD

**Issue by pantovad** [opendistro-for-elasticsearch/performance-analyzer#154]
Here is the process running inside docker container:
`elastic+   164  1.3  0.3 2890216 128268 ?      Sl   13:12   0:46 /opt/jdk/bin/java -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m -Des.path.home=/usr/share/elasticsearch -Dlog4j.configurationFile=/usr/share/elasticsearch/performance-analyzer-rca/pa_config/log4j2.xml -DconfigFilePath=/usr/share/elasticsearch/performance-analyzer-rca/pa_config/performance-analyzer.properties -classpath /usr/share/elasticsearch/performance-analyzer-rca/lib/performance-analyzer-rca-1.3.0-SNAPSHOT.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/jooq-3.10.8.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/bcpkix-jdk15on-1.60.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/bcprov-jdk15on-1.60.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/sqlite-jdbc-3.8.11.2.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-protobuf-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-stub-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-netty-shaded-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-core-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-protobuf-lite-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-api-1.25.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/guava-28.1-jre.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/jackson-databind-2.8.11.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/jackson-annotations-2.8.11.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/log4j-core-2.13.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/log4j-api-2.13.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/commons-lang3-3.9.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/commons-io-2.3.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/javax.annotation-api-1.3.2.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/failureaccess-1.0.1.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/perfmark-api-0.19.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/jsr305-3.0.2.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/checker-qual-2.8.1.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/error_prone_annotations-2.3.3.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/j2objc-annotations-1.3.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/animal-sniffer-annotations-1.18.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/jackson-core-2.8.10.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/protobuf-java-3.10.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/proto-google-common-protos-1.12.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/gson-2.8.5.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/annotations-4.1.1.4.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/opencensus-contrib-grpc-metrics-0.21.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/opencensus-api-0.21.0.jar:/usr/share/elasticsearch/performance-analyzer-rca/lib/grpc-context-1.25.0.jar com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp`

It uses as config: -DconfigFilePath=/usr/share/elasticsearch/performance-analyzer-rca/pa_config/performance-analyzer.properties

And the config is:
```
# ======================== Elasticsearch performance analyzer plugin config =========================

# NOTE: this is an example for Linux. Please modify the config accordingly if you are using it under other OS.

# Metrics data location
metrics-location = /dev/shm/performanceanalyzer/

# Metrics deletion interval (minutes) for metrics data.
# Interval should be between 1 to 60.
metrics-deletion-interval = 1

# If set to true, the system cleans up the files behind it. So at any point, we should expect only 2
# metrics-db-file-prefix-path files. If set to false, no files are cleaned up. This can be useful, if you are archiving
# the files and wouldn't like for them to be cleaned up.
cleanup-metrics-db-files = true

# WebService exposed by App's port
webservice-listener-port = 9600

# Metric DB File Prefix Path location
metrics-db-file-prefix-path = /tmp/metricsdb_

https-enabled = false

#Setup the correct path for certificates
certificate-file-path = specify_path

private-key-file-path = specify_path

# WebService bind host; default only to local interface
webservice-bind-host = 0.0.0.0

# Plugin Stats Metadata file name, expected to be in the same location
plugin-stats-metadata = plugin-stats-metadata

# Agent Stats Metadata file name, expected to be in the same location
agent-stats-metadata = agent-stats-metadata
```

Still the perf analyzer is not binding to 0.0.0.0 but localhost:
```
[root@03d8f890f93b pa_config]# ss -l -n -t
State      Recv-Q Send-Q                                      Local Address:Port                                                     Peer Address:Port              
LISTEN     0      1                                               127.0.0.1:9600                                                                *:*                  
LISTEN     0      128                                            127.0.0.11:33539                                                               *:*                  
LISTEN     0      128                                                     *:9200                                                                *:*                  
LISTEN     0      128                                                     *:9650                                                                *:*                  
LISTEN     0      128                                                     *:9300                                                                *:*   
```

**Comment by daachi** [comment]
I've run into this issue as well, and [the suggestion made in the documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/), to change the configuration and kill/restart the agent, has no effect.

I have been working on a solution to this and had hoped to PR a fix, but if someone else is looking at it too, that would be good to know. At this point, I'm seeing that an attempt to restart the process says 'cannot bind to address' an am trying to work through that.

**Comment by daachi** [comment]
I'm now getting this error when performance_analyzer starts in supervisord:

`18:35:31.247 [main] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.config.PluginSettings - Loading config file /usr/share/elasticsearch/performance-analyzer-rca/pa_config/performance-analyzer.properties failed with error: com.amazon.opendistro.elasticsearch.performanceanalyzer.config.ConfigFileException: java.io.FileNotFoundException: /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/usr/share/elasticsearch/performance-analyzer-rca/pa_config/performance-analyzer.properties (No such file or directory). Using default values.`

**Comment by sendkb** [comment]
Thanks pantovad@ and daachi@ for reporting the issue.  We will look into it and get back to you.  Please send a PR if you have a fix and we would be happy to take it.

**Comment by nandogravina** [comment]
I found this solution inside an OKD image, I did this in all the es nodes
mkdir -p /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/usr/share/elasticsearch/performance-analyzer-rca/pa_config/
cd /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config
cp performance-analyzer.properties /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/usr/share/elasticsearch/performance-analyzer-rca/pa_config/

**Comment by sruti1312** [comment]
Easy way to remediate this would be to modify the configFilePath value in the performance-analyzer-agent file. We need to remove $ES_HOME/performance-analyzer-rca/ because it added by the reader.

Reference: https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/commit/690b69c72991587c614192a57085f028ca52d2ba

It is patched with the next release. 

Thanks.

**Comment by evgeny-sem** [comment]
@sruti1312 Thanks for fixing it. 
But I see that same pattern is used for log4j config file:  -Dlog4j.configurationFile=$ES_HOME/performance-analyzer-rca/pa_config/log4j2.xml
Should not it be fixed as well?

**Comment by sruti1312** [comment]
Currently, only ConfigFilePath uses relativePath that is causing this issue. I am working on modifying it to use absolute path (similar to log4j).

Thanks.
