### ISSUE TITLE
question about /dev/shm size

### ISSUE THREAD

**Issue by HagunKim** [opendistro-for-elasticsearch/performance-analyzer#173]
I saw this on your docs:
Performance Analyzer uses /dev/shm for temporary storage. During heavy workloads on a cluster, Performance Analyzer can use up to 1 GB of space.
Docker, however, has a default /dev/shm size of 64 MB. To change this value, you can use the docker run --shm-size 1gb flag or a similar setting in Docker Compose.

If I use Opendistro ES via helm chart and there are 3 ES master pods and 3 ES data pods in a cluster, which pod's /dev/shm size should I set?

**Comment by ktkrg** [comment]
1GB is an extremely high limit. In case you reach this limit, try setting it on all pods.

**Comment by HagunKim** [comment]
> 1GB is an extremely high limit. In case you reach this limit, try setting it on all pods.

Thanks for your reply.
