### ISSUE TITLE
plugin doesn't work if port 9650 not opened - 1.9.0

### ISSUE THREAD

**Issue by JujuElk** [opendistro-for-elasticsearch/performance-analyzer#205]
Hello, 

Since 1.9.0 version, root cause analysis is communicating with performance analyser through port 9650. If this port is not open, the plugin crash. **Anywhere in your documentation you mentioned this port**. Users who not having this port opened by default will face the crash. 

Thanks, 
Julien Elk

**Comment by zeising** [comment]
I have also stumbled on this. Unfortunately, opening 9650 is not an option.
I'm getting a ton of log spam in /tmp/PerformanceAnalyzer.log because of this, which is filling up the partition.
Is there any way to disable this behavior?
I'm on opendistro 1.10.1.

**Comment by zeising** [comment]
Ping?
This is still an issue, and spam logs in are filling up /tmp.
What is port 9650 used for? There is, as far as I can tell, no documentation about it. How can I configure it to use TLS, and how can I configure the logs to go somewhere other than /tmp?
If it's not possible, how can I disable the plugin completely, to avoid having it filling up /tmp ?

**Comment by WennySoft** [comment]
I also hit this issue. Port 9650 is blocked in firewall but on the other side there is nothing listening on it on the destination server?
What should we do?

(attached a log output)

Additionally there seems to be some files missing (see systemd-output attached)
[ODFE-205.txt](https://github.com/opendistro-for-elasticsearch/performance-analyzer/files/5459677/ODFE-205.txt)

**Comment by zeising** [comment]
I have managed to stop and disable opendistro-performance-analyzer (`systemctl stop opendistro-performance-analyzer`), which stops the log spam, at least. It also disables the performance analyzer though.

**Comment by aditjind** [comment]
Hey zeising@ 

You can set up the new log directory in the file _log4j2.xml_ which is present in directories:

_/usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config
/usr/share/elasticsearch/performance-analyzer-rca/pa_config_

The parameter _File Name_ with value `PerformanceAnalyzerLog` contains the path for the ```PerformanceAnalyzer.Log```
and with value `StatsLog` contains the path for the ```performance_analyzer_agent_stats.log```

By default both of them are set to ```/tmp/...```. You can modify it to whatever location you like and update both log4j2.xml in both the directories.

Restart the ES process should make the plugins pick up the new log directory. This solves the log directory problem. 

We use the port number 9650 for internal node to node communication to transfer data between the nodes. Currently this is non configurable. We already have this on our roadmap to make it configurable. 

Thanks, 
Aditya

**Comment by zeising** [comment]
Hi @aditjind!
I have disabled the performance monitor for now, but I'll look into changing where it stores log.
Will it also be possible to protect the traffic on 9650 using TLS in a future update?

**Comment by aditjind** [comment]
Hey zeising@

We currently have encryption in transit [support](https://github.com/opendistro-for-elasticsearch/performance-analyzer/blob/master/pa_config/performance-analyzer.properties#L18) for client and server communication (Rest and GRPC calls). We will support client authentication as well in the upcoming release. 

The support to have the GRPC port as configurable will also be added. [This PR](https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/pull/508) is currently in review. 

Thank you!

**Comment by zeising** [comment]
I can't see how the link you provided tells me how to protect 9650 using TLS.

**Comment by aditjind** [comment]
Apologies, updated the [link](https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/blob/master/INSTALL.md#5-optional-encryption-in-transit-setup).
