### ISSUE TITLE
Cluster heath metrics in performance analyzer plugin

### ISSUE THREAD

**Issue by dharadesair** [opendistro-for-elasticsearch/performance-analyzer#25]
I was planning to onboard OpenDistro performance analyzer plugin but observed that it is missing some metrics our existing system is collecting.  I observed that "pendingTasks" on master node are collected but following I couldn't find other cluster health metrics
- "number_of_nodes"
- "number_of_data_nodes"
- "active_primary_shards"
- "active_shards"
- "relocating_shards"
- "initializing_shards"
- "unassigned_shards"
- "delayed_unassigned_shards"
- "number_of_in_flight_fetch"
- "task_max_waiting_in_queue_millis"
- "active_shards_percent_as_number"

Is there a plan to collect this from ESResource in future?

**Comment by kdinta** [comment]
We designed the metrics for diagnosability, hence we didn't include all the metrics. We continue to add metrics that has diagnosis value and will consider this list

Note that number_of_pending_tasks : We captured this as 'Master_PendingQueueSize'; please refer https://opendistro.github.io/for-elasticsearch-docs/docs/pa/reference/
