### ISSUE TITLE
Can't build with official gradle docker image, using openJDK 11

### ISSUE THREAD

**Issue by athoune** [opendistro-for-elasticsearch/performance-analyzer#46]
I download and decompress the 0.9 snapshot.

```
docker run -ti --rm -v `pwd`/performance-analyzer-0.9.0.0:/opt/performance-analyzer-0.9.0.0 -w /opt/performance-analyzer-0.9.0.0 gradle:jdk11-slim bash
$ gradle build
```
Lots of output, and :
```
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > the compiler java.home must be set to a JDK installation directory for Java 12 but is [/docker-java-home] corresponding to [11]
```

Java 11 is the version mentioned in your documentation (and the version in next stable Debian).

**Comment by allenyin96** [comment]
Hi,

opendistro-for-elasticsearch 0.9.0 is not officially released yet and the documentation is still referring to 0.8.

opendistro-for-elasticsearch 0.9.0 is built against ES6.7.1, which requires Java 12. So if you want to try it out now please install Java 12 and let us know if you have any further issues.

Thanks

**Comment by tishma** [comment]
Quite disappointing to hear that an official version of ES requires a non-LTS version of Java. Probably aiming at next LTS version eventually. So, we drop to 6.6 in order to use Java 11 I guess.
