### ISSUE TITLE
how to make performance-analyzer working.

### ISSUE THREAD

**Issue by wty1993abc** [opendistro-for-elasticsearch/performance-analyzer#59]
I have unzip performance-analyzer-0.8.0.0.zip in elasticsearch/plugins,but elasticsearch can't run,the error is
Could not load plugin descriptor for plugin directory [performance-analyzer-0.8.0.0]

**Comment by sendkb** [comment]
hi,
   can you try ``` sudo bin/elasticsearch-plugin install opendistro_performance_analyzer```. It should setup the plugin descriptors appropriately. Also please ensure that the ES version that you are using ES 6.6.x with 0.8.0.0 version of performance-analyzer plugin
