### ISSUE TITLE
Dashboards to be used in Kibana

### ISSUE THREAD

**Issue by servergeeks** [opendistro-for-elasticsearch/performance-analyzer#77]
Hello everyone,

Can anyone share some dashboards in order to be imported into kibana? 
I mean ones that use the PA metrics exported via pa-to-es....

Thanks!

br

**Comment by sendkb** [comment]
hi @servergeeks, 
   Are you still looking for the dashboards to be imported into Kibana. 

Thanks !

**Comment by servergeeks** [comment]
Hi @sendkb 

Yes. I am looking for premade dashboards can be used for PA generated metrics.

br

**Comment by aditjind** [comment]
Sorry we don't have any such pre-made dashboards available.
