### ISSUE TITLE
Log level verbosity of cluster

### ISSUE THREAD

**Issue by Lyr** [opendistro-for-elasticsearch/performance-analyzer#98]
In a fresh opendistro cluster that works fine, but when change verbosity to disable some traces in log and some lines are still written in log file.

The lines of log look like this :

```
 [2020-04-22T10:09:17,502][INFO ][stats_log                ] [myhost01] ------------------------------------------------------------------------
Program=PerformanceAnalyzerPlugin
StartTime=1580542897.428
EndTime=Wed, 21 Apr 2020 10:09:17 CEST
Time=60074 msecs
Timing=total-time:60074.0/1
Counters=TotalError=0
EOE
```
It's clearly written by the PerformanceAnalyzer Plugin provided by opendistro, so I try to change the log config/log4j2.properties of this plugin and I've restarted the master (myhost01 in this example) but no change in log.

Version opendistro used : 1.4.0

**Comment by CodeGlitcher** [comment]
Stil having this issue on 1.9.0
Any updates?

**Comment by sgavrylenko** [comment]
yes, we still have this issue in v1.9.0

**Comment by aditjind** [comment]
There are 2 directories where you should update the log4j.xml file:

```
/usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config
/usr/share/elasticsearch/performance-analyzer-rca/pa_config
```

Both of them have a similar structure for the log files. Once you update the log level in both of these files on the node on which you are observing the log and restart the plugin on the node you should be able to see the log level updated in the log files.

**Comment by leonsery** [comment]
![image](https://user-images.githubusercontent.com/27145550/101622422-b3362780-3a1f-11eb-8397-1f4272fbf1cd.png)
There are only the following files. 
Changed in xml and properties from info to error. Restarting elasticsearch service - the same issue remained.

**Comment by ottojwittner** [comment]
Setting `rootLogger.level = warn` in `/etc/elasticsearch/log4j2.properties` makes the performance_analyser go quiet, but obviously also effects all other reporting.

**Comment by pentlander** [comment]
Changing the two `log4j.xml` files mentioned above also did nothing for me. The fix was to add the following lines to the main Elasticsearch `log4j2.properties` file: 
```
logger.perfplugin.name = stats_log
logger.perfplugin.level = error
```

As per: https://www.elastic.co/guide/en/elasticsearch///reference/6.8/logging.html#configuring-logging-levels
